spring.application.name=Food_WebApp

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/food_db
spring.datasource.username=postgres
spring.datasource.password=12345

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

aws.s3.endpoint=http://localhost:4566
aws.s3.region=us-east-1
aws.s3.bucket=foodcode

aws.s3.access-key=test
aws.s3.secret-key=test

jwt.secret=D+6p5SoqX7Hi8STZi4c3MmdhK1M4/6Icf60z4ubuh20=


